### ISSUE TITLE
Add a new route for PyCon Blog

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/magudi#39]
The base URL for the Navbar is "https://in.pycon.org/2020/" + "whatever comes next"
The BLOG_URL is https://in.pycon.org/blog

So if we can add a new path for Nginx --> https://in.pycon.org/2020/blog that redirects to the BLOG_URL
I am opening a new PR there, thanks!

**Comment by palnabarun** [comment]
@vipulgupta2048 -- that is a hack I would say. The correct solution is what is done in https://github.com/pythonindia/inpycon2020/pull/38

**Comment by vipulgupta2048** [comment]
Yes, I agree. Closing :+1:
